server:
  port: 8083
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/semi
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: semi
#    password: semi
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 872355310097-us4s0i239pm42eog5c78dc7qcg6hc00k.apps.googleusercontent.com
#            client-secret: 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
#            scope: email, profile

#google cloud 연결 설정 추가
spring:
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:semiproject.json
        project-id: "semiproject-408200"
        bucket: petteles
  datasource:
    url: jdbc:mysql://222.112.124.237:3306/pettales
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pettales
    password: pettales
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 872355310097-us4s0i239pm42eog5c78dc7qcg6hc00k.apps.googleusercontent.com
              client-secret: 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
              scope: email, profile
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false # 개발 중에는 이 옵션을 false로 설정하여 캐시를 비활성화
    mode: HTML5 # Thymeleaf 3.x 버전에서는 HTML 이라고만 적어도 됩니다.
    encoding: UTF-8
    check-template-location: true
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show_sql: true
mybatis:
  mapper-locations: classpath:resources/mapper/**/*.xml
  config-location: classpath:mapper/mapper-config.xml

#mybatis:
#  mapper-locations: mapper/*.xml

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/petales
#    username: petales
#    password: petales


#thymeleaf:
#  prefix=classpath: templates/
#  suffix: .html
#  check-template-location: true
#  cache: false
#  mvc:
#    static-path-pattern: "/static/**"

